# Generated by Django 4.0.4 on 2022-05-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
    ]
