# Generated by Django 4.0.4 on 2022-05-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_inventory_item_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
