# Generated by Django 4.0.4 on 2022-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
