# Generated by Django 4.0.4 on 2022-05-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_shop_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('NOOB', 'Out of Box'), ('Damaged', 'Damaged'), ('For Parts', 'For Parts'), ('SAI', 'Sold As Is')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Women', 'W'), ('Men', 'M'), ('Kids', 'Kids'), ('Home', 'H'), ('Vintage & Collectible', 'V&C'), ('Beauty', 'B'), ('Electronics', 'E'), ('Sports & Outdoors', 'S&O'), ('Handmade', 'HM'), ('Other', 'O')], max_length=150),
        ),
    ]
